Fix the case of the missing --timestamp
>>> '{} {} {}'.format(1, 2)
  IndexError: tuple index out of range

>>> '{} {} {}'.format(1, 2, 3, 4)
    '1 2 3'

TODO: Write tests to avoid this sort of thing